using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ID3.Utils
{
    public class LanguageTable
    {
        public static IDictionary<string, string> Languages
        {
            get
            {
                if (dictionary == null)
                {
                    FillDictionary();
                }

                return dictionary;
            }
        }
        public static IList<string> LanguagesCodes
        {
            get
            {
                if (languageCodes == null)
                {
                    languageCodes = Languages.Keys.ToList();
                }

                return languageCodes;
            }
        }

        private static Dictionary<string, string> dictionary = null;
        private static List<string> languageCodes = null;
        private static void FillDictionary()
        {
            dictionary = new Dictionary<string, string>();

            dictionary.Add("aar", "Afar");
            dictionary.Add("abk", "Abkhazian");
            dictionary.Add("ace", "Achinese");
            dictionary.Add("ach", "Acoli");
            dictionary.Add("ada", "Adangme");
            dictionary.Add("ady", "Adyghe; Adygei");
            dictionary.Add("afa", "Afro-Asiatic languages");
            dictionary.Add("afh", "Afrihili");
            dictionary.Add("afr", "Afrikaans");
            dictionary.Add("ain", "Ainu");
            dictionary.Add("aka", "Akan");
            dictionary.Add("akk", "Akkadian");
            dictionary.Add("alb", "Albanian");
            dictionary.Add("ale", "Aleut");
            dictionary.Add("alg", "Algonquian languages");
            dictionary.Add("alt", "Southern Altai");
            dictionary.Add("amh", "Amharic");
            dictionary.Add("ang", "English, Old (ca.450-1100)");
            dictionary.Add("anp", "Angika");
            dictionary.Add("apa", "Apache languages");
            dictionary.Add("ara", "Arabic");
            dictionary.Add("arc", "Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE)");
            dictionary.Add("arg", "Aragonese");
            dictionary.Add("arm", "Armenian");
            dictionary.Add("arn", "Mapudungun; Mapuche");
            dictionary.Add("arp", "Arapaho");
            dictionary.Add("art", "Artificial languages");
            dictionary.Add("arw", "Arawak");
            dictionary.Add("asm", "Assamese");
            dictionary.Add("ast", "Asturian; Bable; Leonese; Asturleonese");
            dictionary.Add("ath", "Athapascan languages");
            dictionary.Add("aus", "Australian languages");
            dictionary.Add("ava", "Avaric");
            dictionary.Add("ave", "Avestan");
            dictionary.Add("awa", "Awadhi");
            dictionary.Add("aym", "Aymara");
            dictionary.Add("aze", "Azerbaijani");
            dictionary.Add("bad", "Banda languages");
            dictionary.Add("bai", "Bamileke languages");
            dictionary.Add("bak", "Bashkir");
            dictionary.Add("bal", "Baluchi");
            dictionary.Add("bam", "Bambara");
            dictionary.Add("ban", "Balinese");
            dictionary.Add("baq", "Basque");
            dictionary.Add("bas", "Basa");
            dictionary.Add("bat", "Baltic languages");
            dictionary.Add("bej", "Beja; Bedawiyet");
            dictionary.Add("bel", "Belarusian");
            dictionary.Add("bem", "Bemba");
            dictionary.Add("ben", "Bengali");
            dictionary.Add("ber", "Berber languages");
            dictionary.Add("bho", "Bhojpuri");
            dictionary.Add("bih", "Bihari languages");
            dictionary.Add("bik", "Bikol");
            dictionary.Add("bin", "Bini; Edo");
            dictionary.Add("bis", "Bislama");
            dictionary.Add("bla", "Siksika");
            dictionary.Add("bnt", "Bantu (Other)");
            dictionary.Add("bos", "Bosnian");
            dictionary.Add("bra", "Braj");
            dictionary.Add("bre", "Breton");
            dictionary.Add("btk", "Batak languages");
            dictionary.Add("bua", "Buriat");
            dictionary.Add("bug", "Buginese");
            dictionary.Add("bul", "Bulgarian");
            dictionary.Add("bur", "Burmese");
            dictionary.Add("byn", "Blin; Bilin");
            dictionary.Add("cad", "Caddo");
            dictionary.Add("cai", "Central American Indian languages");
            dictionary.Add("car", "Galibi Carib");
            dictionary.Add("cat", "Catalan; Valencian");
            dictionary.Add("cau", "Caucasian languages");
            dictionary.Add("ceb", "Cebuano");
            dictionary.Add("cel", "Celtic languages");
            dictionary.Add("cha", "Chamorro");
            dictionary.Add("chb", "Chibcha");
            dictionary.Add("che", "Chechen");
            dictionary.Add("chg", "Chagatai");
            dictionary.Add("chi", "Chinese");
            dictionary.Add("chk", "Chuukese");
            dictionary.Add("chm", "Mari");
            dictionary.Add("chn", "Chinook jargon");
            dictionary.Add("cho", "Choctaw");
            dictionary.Add("chp", "Chipewyan; Dene Suline");
            dictionary.Add("chr", "Cherokee");
            dictionary.Add("chu", "Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic");
            dictionary.Add("chv", "Chuvash");
            dictionary.Add("chy", "Cheyenne");
            dictionary.Add("cmc", "Chamic languages");
            dictionary.Add("cop", "Coptic");
            dictionary.Add("cor", "Cornish");
            dictionary.Add("cos", "Corsican");
            dictionary.Add("cpe", "Creoles and pidgins, English based");
            dictionary.Add("cpf", "Creoles and pidgins, French-based ");
            dictionary.Add("cpp", "Creoles and pidgins, Portuguese-based ");
            dictionary.Add("cre", "Cree");
            dictionary.Add("crh", "Crimean Tatar; Crimean Turkish");
            dictionary.Add("crp", "Creoles and pidgins ");
            dictionary.Add("csb", "Kashubian");
            dictionary.Add("cus", "Cushitic languages");
            dictionary.Add("cze", "Czech");
            dictionary.Add("dak", "Dakota");
            dictionary.Add("dan", "Danish");
            dictionary.Add("dar", "Dargwa");
            dictionary.Add("day", "Land Dayak languages");
            dictionary.Add("del", "Delaware");
            dictionary.Add("den", "Slave (Athapascan)");
            dictionary.Add("dgr", "Dogrib");
            dictionary.Add("din", "Dinka");
            dictionary.Add("div", "Divehi; Dhivehi; Maldivian");
            dictionary.Add("doi", "Dogri");
            dictionary.Add("dra", "Dravidian languages");
            dictionary.Add("dsb", "Lower Sorbian");
            dictionary.Add("dua", "Duala");
            dictionary.Add("dum", "Dutch, Middle (ca.1050-1350)");
            dictionary.Add("dut", "Dutch; Flemish");
            dictionary.Add("dyu", "Dyula");
            dictionary.Add("dzo", "Dzongkha");
            dictionary.Add("efi", "Efik");
            dictionary.Add("egy", "Egyptian (Ancient)");
            dictionary.Add("eka", "Ekajuk");
            dictionary.Add("elx", "Elamite");
            dictionary.Add("eng", "English");
            dictionary.Add("enm", "English, Middle (1100-1500)");
            dictionary.Add("epo", "Esperanto");
            dictionary.Add("est", "Estonian");
            dictionary.Add("ewe", "Ewe");
            dictionary.Add("ewo", "Ewondo");
            dictionary.Add("fan", "Fang");
            dictionary.Add("fao", "Faroese");
            dictionary.Add("fat", "Fanti");
            dictionary.Add("fij", "Fijian");
            dictionary.Add("fil", "Filipino; Pilipino");
            dictionary.Add("fin", "Finnish");
            dictionary.Add("fiu", "Finno-Ugrian languages");
            dictionary.Add("fon", "Fon");
            dictionary.Add("fre", "French");
            dictionary.Add("frm", "French, Middle (ca.1400-1600)");
            dictionary.Add("fro", "French, Old (842-ca.1400)");
            dictionary.Add("frr", "Northern Frisian");
            dictionary.Add("frs", "Eastern Frisian");
            dictionary.Add("fry", "Western Frisian");
            dictionary.Add("ful", "Fulah");
            dictionary.Add("fur", "Friulian");
            dictionary.Add("gaa", "Ga");
            dictionary.Add("gay", "Gayo");
            dictionary.Add("gba", "Gbaya");
            dictionary.Add("gem", "Germanic languages");
            dictionary.Add("geo", "Georgian");
            dictionary.Add("ger", "German");
            dictionary.Add("gez", "Geez");
            dictionary.Add("gil", "Gilbertese");
            dictionary.Add("gla", "Gaelic; Scottish Gaelic");
            dictionary.Add("gle", "Irish");
            dictionary.Add("glg", "Galician");
            dictionary.Add("glv", "Manx");
            dictionary.Add("gmh", "German, Middle High (ca.1050-1500)");
            dictionary.Add("goh", "German, Old High (ca.750-1050)");
            dictionary.Add("gon", "Gondi");
            dictionary.Add("gor", "Gorontalo");
            dictionary.Add("got", "Gothic");
            dictionary.Add("grb", "Grebo");
            dictionary.Add("grc", "Greek, Ancient (to 1453)");
            dictionary.Add("gre", "Greek, Modern (1453-)");
            dictionary.Add("grn", "Guarani");
            dictionary.Add("gsw", "Swiss German; Alemannic; Alsatian");
            dictionary.Add("guj", "Gujarati");
            dictionary.Add("gwi", "Gwich'in");
            dictionary.Add("hai", "Haida");
            dictionary.Add("hat", "Haitian; Haitian Creole");
            dictionary.Add("hau", "Hausa");
            dictionary.Add("haw", "Hawaiian");
            dictionary.Add("heb", "Hebrew");
            dictionary.Add("her", "Herero");
            dictionary.Add("hil", "Hiligaynon");
            dictionary.Add("him", "Himachali languages; Western Pahari languages");
            dictionary.Add("hin", "Hindi");
            dictionary.Add("hit", "Hittite");
            dictionary.Add("hmn", "Hmong");
            dictionary.Add("hmo", "Hiri Motu");
            dictionary.Add("hrv", "Croatian");
            dictionary.Add("hsb", "Upper Sorbian");
            dictionary.Add("hun", "Hungarian");
            dictionary.Add("hup", "Hupa");
            dictionary.Add("iba", "Iban");
            dictionary.Add("ibo", "Igbo");
            dictionary.Add("ice", "Icelandic");
            dictionary.Add("ido", "Ido");
            dictionary.Add("iii", "Sichuan Yi; Nuosu");
            dictionary.Add("ijo", "Ijo languages");
            dictionary.Add("iku", "Inuktitut");
            dictionary.Add("ile", "Interlingue; Occidental");
            dictionary.Add("ilo", "Iloko");
            dictionary.Add("ina", "Interlingua (International Auxiliary Language Association)");
            dictionary.Add("inc", "Indic languages");
            dictionary.Add("ind", "Indonesian");
            dictionary.Add("ine", "Indo-European languages");
            dictionary.Add("inh", "Ingush");
            dictionary.Add("ipk", "Inupiaq");
            dictionary.Add("ira", "Iranian languages");
            dictionary.Add("iro", "Iroquoian languages");
            dictionary.Add("ita", "Italian");
            dictionary.Add("jav", "Javanese");
            dictionary.Add("jbo", "Lojban");
            dictionary.Add("jpn", "Japanese");
            dictionary.Add("jpr", "Judeo-Persian");
            dictionary.Add("jrb", "Judeo-Arabic");
            dictionary.Add("kaa", "Kara-Kalpak");
            dictionary.Add("kab", "Kabyle");
            dictionary.Add("kac", "Kachin; Jingpho");
            dictionary.Add("kal", "Kalaallisut; Greenlandic");
            dictionary.Add("kam", "Kamba");
            dictionary.Add("kan", "Kannada");
            dictionary.Add("kar", "Karen languages");
            dictionary.Add("kas", "Kashmiri");
            dictionary.Add("kau", "Kanuri");
            dictionary.Add("kaw", "Kawi");
            dictionary.Add("kaz", "Kazakh");
            dictionary.Add("kbd", "Kabardian");
            dictionary.Add("kha", "Khasi");
            dictionary.Add("khi", "Khoisan languages");
            dictionary.Add("khm", "Central Khmer");
            dictionary.Add("kho", "Khotanese; Sakan");
            dictionary.Add("kik", "Kikuyu; Gikuyu");
            dictionary.Add("kin", "Kinyarwanda");
            dictionary.Add("kir", "Kirghiz; Kyrgyz");
            dictionary.Add("kmb", "Kimbundu");
            dictionary.Add("kok", "Konkani");
            dictionary.Add("kom", "Komi");
            dictionary.Add("kon", "Kongo");
            dictionary.Add("kor", "Korean");
            dictionary.Add("kos", "Kosraean");
            dictionary.Add("kpe", "Kpelle");
            dictionary.Add("krc", "Karachay-Balkar");
            dictionary.Add("krl", "Karelian");
            dictionary.Add("kro", "Kru languages");
            dictionary.Add("kru", "Kurukh");
            dictionary.Add("kua", "Kuanyama; Kwanyama");
            dictionary.Add("kum", "Kumyk");
            dictionary.Add("kur", "Kurdish");
            dictionary.Add("kut", "Kutenai");
            dictionary.Add("lad", "Ladino");
            dictionary.Add("lah", "Lahnda");
            dictionary.Add("lam", "Lamba");
            dictionary.Add("lao", "Lao");
            dictionary.Add("lat", "Latin");
            dictionary.Add("lav", "Latvian");
            dictionary.Add("lez", "Lezghian");
            dictionary.Add("lim", "Limburgan; Limburger; Limburgish");
            dictionary.Add("lin", "Lingala");
            dictionary.Add("lit", "Lithuanian");
            dictionary.Add("lol", "Mongo");
            dictionary.Add("loz", "Lozi");
            dictionary.Add("ltz", "Luxembourgish; Letzeburgesch");
            dictionary.Add("lua", "Luba-Lulua");
            dictionary.Add("lub", "Luba-Katanga");
            dictionary.Add("lug", "Ganda");
            dictionary.Add("lui", "Luiseno");
            dictionary.Add("lun", "Lunda");
            dictionary.Add("luo", "Luo (Kenya and Tanzania)");
            dictionary.Add("lus", "Lushai");
            dictionary.Add("mac", "Macedonian");
            dictionary.Add("mad", "Madurese");
            dictionary.Add("mag", "Magahi");
            dictionary.Add("mah", "Marshallese");
            dictionary.Add("mai", "Maithili");
            dictionary.Add("mak", "Makasar");
            dictionary.Add("mal", "Malayalam");
            dictionary.Add("man", "Mandingo");
            dictionary.Add("mao", "Maori");
            dictionary.Add("map", "Austronesian languages");
            dictionary.Add("mar", "Marathi");
            dictionary.Add("mas", "Masai");
            dictionary.Add("may", "Malay");
            dictionary.Add("mdf", "Moksha");
            dictionary.Add("mdr", "Mandar");
            dictionary.Add("men", "Mende");
            dictionary.Add("mga", "Irish, Middle (900-1200)");
            dictionary.Add("mic", "Mi'kmaq; Micmac");
            dictionary.Add("min", "Minangkabau");
            dictionary.Add("mis", "Uncoded languages");
            dictionary.Add("mkh", "Mon-Khmer languages");
            dictionary.Add("mlg", "Malagasy");
            dictionary.Add("mlt", "Maltese");
            dictionary.Add("mnc", "Manchu");
            dictionary.Add("mni", "Manipuri");
            dictionary.Add("mno", "Manobo languages");
            dictionary.Add("moh", "Mohawk");
            dictionary.Add("mon", "Mongolian");
            dictionary.Add("mos", "Mossi");
            dictionary.Add("mul", "Multiple languages");
            dictionary.Add("mun", "Munda languages");
            dictionary.Add("mus", "Creek");
            dictionary.Add("mwl", "Mirandese");
            dictionary.Add("mwr", "Marwari");
            dictionary.Add("myn", "Mayan languages");
            dictionary.Add("myv", "Erzya");
            dictionary.Add("nah", "Nahuatl languages");
            dictionary.Add("nai", "North American Indian languages");
            dictionary.Add("nap", "Neapolitan");
            dictionary.Add("nau", "Nauru");
            dictionary.Add("nav", "Navajo; Navaho");
            dictionary.Add("nbl", "Ndebele, South; South Ndebele");
            dictionary.Add("nde", "Ndebele, North; North Ndebele");
            dictionary.Add("ndo", "Ndonga");
            dictionary.Add("nds", "Low German; Low Saxon; German, Low; Saxon, Low");
            dictionary.Add("nep", "Nepali");
            dictionary.Add("new", "Nepal Bhasa; Newari");
            dictionary.Add("nia", "Nias");
            dictionary.Add("nic", "Niger-Kordofanian languages");
            dictionary.Add("niu", "Niuean");
            dictionary.Add("nno", "Norwegian Nynorsk; Nynorsk, Norwegian");
            dictionary.Add("nob", "Bokmål, Norwegian; Norwegian Bokmål");
            dictionary.Add("nog", "Nogai");
            dictionary.Add("non", "Norse, Old");
            dictionary.Add("nor", "Norwegian");
            dictionary.Add("nqo", "N'Ko");
            dictionary.Add("nso", "Pedi; Sepedi; Northern Sotho");
            dictionary.Add("nub", "Nubian languages");
            dictionary.Add("nwc", "Classical Newari; Old Newari; Classical Nepal Bhasa");
            dictionary.Add("nya", "Chichewa; Chewa; Nyanja");
            dictionary.Add("nym", "Nyamwezi");
            dictionary.Add("nyn", "Nyankole");
            dictionary.Add("nyo", "Nyoro");
            dictionary.Add("nzi", "Nzima");
            dictionary.Add("oci", "Occitan (post 1500); Provençal");
            dictionary.Add("oji", "Ojibwa");
            dictionary.Add("ori", "Oriya");
            dictionary.Add("orm", "Oromo");
            dictionary.Add("osa", "Osage");
            dictionary.Add("oss", "Ossetian; Ossetic");
            dictionary.Add("ota", "Turkish, Ottoman (1500-1928)");
            dictionary.Add("oto", "Otomian languages");
            dictionary.Add("paa", "Papuan languages");
            dictionary.Add("pag", "Pangasinan");
            dictionary.Add("pal", "Pahlavi");
            dictionary.Add("pam", "Pampanga; Kapampangan");
            dictionary.Add("pan", "Panjabi; Punjabi");
            dictionary.Add("pap", "Papiamento");
            dictionary.Add("pau", "Palauan");
            dictionary.Add("peo", "Persian, Old (ca.600-400 B.C.)");
            dictionary.Add("per", "Persian");
            dictionary.Add("phi", "Philippine languages");
            dictionary.Add("phn", "Phoenician");
            dictionary.Add("pli", "Pali");
            dictionary.Add("pol", "Polish");
            dictionary.Add("pon", "Pohnpeian");
            dictionary.Add("por", "Portuguese");
            dictionary.Add("pra", "Prakrit languages");
            dictionary.Add("pro", "Provençal, Old (to 1500)");
            dictionary.Add("pus", "Pushto; Pashto");
            dictionary.Add("qaa", "Reserved for local use");
            dictionary.Add("que", "Quechua");
            dictionary.Add("raj", "Rajasthani");
            dictionary.Add("rap", "Rapanui");
            dictionary.Add("rar", "Rarotongan; Cook Islands Maori");
            dictionary.Add("roa", "Romance languages");
            dictionary.Add("roh", "Romansh");
            dictionary.Add("rom", "Romany");
            dictionary.Add("rum", "Romanian; Moldavian; Moldovan");
            dictionary.Add("run", "Rundi");
            dictionary.Add("rup", "Aromanian; Arumanian; Macedo-Romanian");
            dictionary.Add("rus", "Russian");
            dictionary.Add("sad", "Sandawe");
            dictionary.Add("sag", "Sango");
            dictionary.Add("sah", "Yakut");
            dictionary.Add("sai", "South American Indian (Other)");
            dictionary.Add("sal", "Salishan languages");
            dictionary.Add("sam", "Samaritan Aramaic");
            dictionary.Add("san", "Sanskrit");
            dictionary.Add("sas", "Sasak");
            dictionary.Add("sat", "Santali");
            dictionary.Add("scn", "Sicilian");
            dictionary.Add("sco", "Scots");
            dictionary.Add("sel", "Selkup");
            dictionary.Add("sem", "Semitic languages");
            dictionary.Add("sga", "Irish, Old (to 900)");
            dictionary.Add("sgn", "Sign Languages");
            dictionary.Add("shn", "Shan");
            dictionary.Add("sid", "Sidamo");
            dictionary.Add("sin", "Sinhala; Sinhalese");
            dictionary.Add("sio", "Siouan languages");
            dictionary.Add("sit", "Sino-Tibetan languages");
            dictionary.Add("sla", "Slavic languages");
            dictionary.Add("slo", "Slovak");
            dictionary.Add("slv", "Slovenian");
            dictionary.Add("sma", "Southern Sami");
            dictionary.Add("sme", "Northern Sami");
            dictionary.Add("smi", "Sami languages");
            dictionary.Add("smj", "Lule Sami");
            dictionary.Add("smn", "Inari Sami");
            dictionary.Add("smo", "Samoan");
            dictionary.Add("sms", "Skolt Sami");
            dictionary.Add("sna", "Shona");
            dictionary.Add("snd", "Sindhi");
            dictionary.Add("snk", "Soninke");
            dictionary.Add("sog", "Sogdian");
            dictionary.Add("som", "Somali");
            dictionary.Add("son", "Songhai languages");
            dictionary.Add("sot", "Sotho, Southern");
            dictionary.Add("spa", "Spanish; Castilian");
            dictionary.Add("srd", "Sardinian");
            dictionary.Add("srn", "Sranan Tongo");
            dictionary.Add("srp", "Serbian");
            dictionary.Add("srr", "Serer");
            dictionary.Add("ssa", "Nilo-Saharan languages");
            dictionary.Add("ssw", "Swati");
            dictionary.Add("suk", "Sukuma");
            dictionary.Add("sun", "Sundanese");
            dictionary.Add("sus", "Susu");
            dictionary.Add("sux", "Sumerian");
            dictionary.Add("swa", "Swahili");
            dictionary.Add("swe", "Swedish");
            dictionary.Add("syc", "Classical Syriac");
            dictionary.Add("syr", "Syriac");
            dictionary.Add("tah", "Tahitian");
            dictionary.Add("tai", "Tai languages");
            dictionary.Add("tam", "Tamil");
            dictionary.Add("tat", "Tatar");
            dictionary.Add("tel", "Telugu");
            dictionary.Add("tem", "Timne");
            dictionary.Add("ter", "Tereno");
            dictionary.Add("tet", "Tetum");
            dictionary.Add("tgk", "Tajik");
            dictionary.Add("tgl", "Tagalog");
            dictionary.Add("tha", "Thai");
            dictionary.Add("tib", "Tibetan");
            dictionary.Add("tig", "Tigre");
            dictionary.Add("tir", "Tigrinya");
            dictionary.Add("tiv", "Tiv");
            dictionary.Add("tkl", "Tokelau");
            dictionary.Add("tlh", "Klingon; tlhIngan-Hol");
            dictionary.Add("tli", "Tlingit");
            dictionary.Add("tmh", "Tamashek");
            dictionary.Add("tog", "Tonga (Nyasa)");
            dictionary.Add("ton", "Tonga (Tonga Islands)");
            dictionary.Add("tpi", "Tok Pisin");
            dictionary.Add("tsi", "Tsimshian");
            dictionary.Add("tsn", "Tswana");
            dictionary.Add("tso", "Tsonga");
            dictionary.Add("tuk", "Turkmen");
            dictionary.Add("tum", "Tumbuka");
            dictionary.Add("tup", "Tupi languages");
            dictionary.Add("tur", "Turkish");
            dictionary.Add("tut", "Altaic languages");
            dictionary.Add("tvl", "Tuvalu");
            dictionary.Add("twi", "Twi");
            dictionary.Add("tyv", "Tuvinian");
            dictionary.Add("udm", "Udmurt");
            dictionary.Add("uga", "Ugaritic");
            dictionary.Add("uig", "Uighur; Uyghur");
            dictionary.Add("ukr", "Ukrainian");
            dictionary.Add("umb", "Umbundu");
            dictionary.Add("und", "Undetermined");
            dictionary.Add("urd", "Urdu");
            dictionary.Add("uzb", "Uzbek");
            dictionary.Add("vai", "Vai");
            dictionary.Add("ven", "Venda");
            dictionary.Add("vie", "Vietnamese");
            dictionary.Add("vol", "Volapük");
            dictionary.Add("vot", "Votic");
            dictionary.Add("wak", "Wakashan languages");
            dictionary.Add("wal", "Walamo");
            dictionary.Add("war", "Waray");
            dictionary.Add("was", "Washo");
            dictionary.Add("wel", "Welsh");
            dictionary.Add("wen", "Sorbian languages");
            dictionary.Add("wln", "Walloon");
            dictionary.Add("wol", "Wolof");
            dictionary.Add("xal", "Kalmyk; Oirat");
            dictionary.Add("xho", "Xhosa");
            dictionary.Add("yao", "Yao");
            dictionary.Add("yap", "Yapese");
            dictionary.Add("yid", "Yiddish");
            dictionary.Add("yor", "Yoruba");
            dictionary.Add("ypk", "Yupik languages");
            dictionary.Add("zap", "Zapotec");
            dictionary.Add("zbl", "Blissymbols; Blissymbolics; Bliss");
            dictionary.Add("zen", "Zenaga");
            dictionary.Add("zha", "Zhuang; Chuang");
            dictionary.Add("znd", "Zande languages");
            dictionary.Add("zul", "Zulu");
            dictionary.Add("zun", "Zuni");
            dictionary.Add("zxx", "No linguistic content; Not applicable");
            dictionary.Add("zza", "Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki");
        }
        // Code to parse language file from http://www.loc.gov/standards/iso639-2/ascii_8bits.html

        //static void Main(string[] args)
        //{
        //    Dictionary<string, string> dic = new Dictionary<string, string>();

        //    System.IO.StreamReader re = System.IO.File.OpenText("d:\\ISO-639-2_utf-8.txt");

        //    string input = null;
        //    while ((input = re.ReadLine()) != null)
        //    {
        //        string[] strs = input.Split('|');

        //        dic.Add(strs[0], strs[3]);

        //        Console.Write("            dictionary.Add(\"");
        //        Console.Write(strs[0].Substring(0, 3));
        //        Console.Write("\", ");

        //        Console.Write("\"");
        //        Console.Write(strs[3]);
        //        Console.Write("\");\n");
        //    }
        //}
    }


}
